name: Auto Build ImmortalWrt

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch: # 允许手动触发

jobs:
  auto-build:
    runs-on: ubuntu-latest

    steps:
        -   uses: actions/checkout@v2

        - name: Prepare Environment
          run: |
            sudo apt update -y
            sudo apt full-upgrade -y
            sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
                bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
                g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
                libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
                libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
                ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
                python3-pyelftools qemu-utils re2c rsync scons squashfs-tools mkisofs subversion swig texinfo uglifyjs \
                upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

        - name: Build
          run: |
            bash build.sh
        
        - name: Delete previous release
          run: gh release delete weekly --cleanup-tag --yes
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          continue-on-error: true

        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: "weekly"
            name: "Weekly ImmortalWrt Build"
            body: |
              **Automated Weekly Build**
              
              - Triggered by: ${{ github.event_name }}
              - Commit: `${{ github.sha }}`
              - Build Time: `$(date)`
            draft: false
            prerelease: false
            files: immortalwrt/bin/targets/**/*.*